(defhydradio pandoc-binary ()
  (standalone "St_a_ndalone" [yes no])
  (preserve-tabs "Preserve _T_abs" [yes no])
  (strict "_S_trict" [yes no])
  (normalize "Normali_z_e Document" [yes no])
  (reference-links "Reference _L_inks" [yes no])
  (parse-raw "Parse _R_aw" [yes no])
  (smart "S_m_art" [yes no])
  (gladtex "_g_ladTeX" [yes no])
  (incremental "_I_ncremental" [yes no])
  (self-contained "Self-contained _D_ocument" [yes no])
  (chapters "Top-level Headers Are _C_hapters" [yes no])
  (number-sections "N_u_mber Sections" [yes no])
  (listings "LaTeX _l_istings Package" [on off])
  (section-divs "Wrap Sections in <_d_iv> Tags" [yes no])
  (wrap "_W_rap" [no yes])
  (highlight "_H_ighlighting" [no yes])
  (table-of-contents "Table of C_o_ntents" [yes no])
  (natbib "_N_atBib" [yes no])
  (biblatex "_B_ibLaTeX" [yes no])
  (ascii "Only _A_SCII in HTML" [yes no])
  (atx-headers "AT_X_-style Headers" [yes no])
  (old-dashes "_O_ld-style Dashes" [yes no])
  (tex-ligatures "T_e_X Ligatures" [yes no])
  (html-q-tags "<_q_> Tags for Quotes in HTML" [yes no]))

(defhydra pandoc-binary ()
  (concat (hydra--table pandoc-binary/names 8 3 " % -34s %% -3`%s ")
          "\n\n")
  ("a" (pandoc-binary/standalone) nil)
  ("T" (pandoc-binary/preserve-tabs) nil)
  ("S" (pandoc-binary/strict) nil)
  ("z" (pandoc-binary/normalize) nil)
  ("L" (pandoc-binary/reference-links) nil)
  ("R" (pandoc-binary/parse-raw) nil)
  ("m" (pandoc-binary/smart) nil)
  ("g" (pandoc-binary/gladtex) nil)
  ("I" (pandoc-binary/incremental) nil)
  ("D" (pandoc-binary/self-contained) nil)
  ("C" (pandoc-binary/chapters) nil)
  ("u" (pandoc-binary/number-sections) nil)
  ("l" (pandoc-binary/listings) nil)
  ("d" (pandoc-binary/section-divs) nil)
  ("W" (pandoc-binary/wrap) nil)
  ("H" (pandoc-binary/highlight) nil)
  ("o" (pandoc-binary/table-of-contents) nil)
  ("N" (pandoc-binary/natbib) nil)
  ("B" (pandoc-binary/biblatex) nil)
  ("A" (pandoc-binary/ascii) nil)
  ("X" (pandoc-binary/atx-headers) nil)
  ("O" (pandoc-binary/old-dashes) nil)
  ("e" (pandoc-binary/tex-ligatures) nil)
  ("q" (pandoc-binary/html-q-tags) nil)
  ("r" (hydra-reset-radios pandoc-binary/names) "reset"))

(global-set-key (kbd "C-c C-,") 'pandoc-binary/body)
